[2023-10-01 01:11:14,305] 	INFO 	22 	id_data.py 	<module>() 	ID Data Started
[2023-10-01 01:12:42,404] 	ERROR 	79 	id_data.py 	<module>() 	Error occurred during ID Data process. Error: 521 Server Error:  for url: https://endpoints.omniatech.io/v1/arbitrum/one/public
[2023-10-01 12:25:49,105] 	INFO 	22 	id_data.py 	<module>() 	ID Data Started
[2023-10-01 12:27:45,544] 	ERROR 	79 	id_data.py 	<module>() 	Error occurred during ID Data process. Error: 521 Server Error:  for url: https://endpoints.omniatech.io/v1/arbitrum/one/public
[2023-10-02 01:03:44,756] 	INFO 	22 	id_data.py 	<module>() 	ID Data Started
[2023-10-02 01:05:17,539] 	ERROR 	79 	id_data.py 	<module>() 	Error occurred during ID Data process. Error: 521 Server Error:  for url: https://endpoints.omniatech.io/v1/arbitrum/one/public
[2023-10-02 12:29:03,108] 	INFO 	22 	id_data.py 	<module>() 	ID Data Started
[2023-10-02 12:30:25,154] 	ERROR 	79 	id_data.py 	<module>() 	Error occurred during ID Data process. Error: 521 Server Error:  for url: https://endpoints.omniatech.io/v1/arbitrum/one/public
[2023-10-03 01:03:55,986] 	INFO 	22 	id_data.py 	<module>() 	ID Data Started
[2023-10-03 01:03:56,643] 	ERROR 	79 	id_data.py 	<module>() 	Error occurred during ID Data process. Error: 521 Server Error:  for url: https://endpoints.omniatech.io/v1/arbitrum/one/public
[2023-10-03 12:28:54,631] 	INFO 	22 	id_data.py 	<module>() 	ID Data Started
[2023-10-03 12:30:42,372] 	ERROR 	79 	id_data.py 	<module>() 	Error occurred during ID Data process. Error: 521 Server Error:  for url: https://endpoints.omniatech.io/v1/arbitrum/one/public
